// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhpvHr0MnNee8mH8aFR-B1sY2mtTIbb8o',
    appId: '1:204991613682:web:959d8c1fa0ba33d4359e6b',
    messagingSenderId: '204991613682',
    projectId: 'shosestore-7c86e',
    authDomain: 'shosestore-7c86e.firebaseapp.com',
    databaseURL: 'https://shosestore-7c86e-default-rtdb.firebaseio.com',
    storageBucket: 'shosestore-7c86e.firebasestorage.app',
    measurementId: 'G-DEFK99L6RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zda2-gApf3BnmmcrbVXwxzdG5Nnx9_M',
    appId: '1:204991613682:android:3dfe2b9fad8bf024359e6b',
    messagingSenderId: '204991613682',
    projectId: 'shosestore-7c86e',
    databaseURL: 'https://shosestore-7c86e-default-rtdb.firebaseio.com',
    storageBucket: 'shosestore-7c86e.firebasestorage.app',
  );
}
